### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by di1l0o** [democritus-project/d8s-xml#10]
We discovered a potential code execution backdoor in version 0.1.0 of the project, the backdoor is the democritus-strings package. Attackers can upload democritus-strings packages containing arbitrary malicious code. For the safety of this project, the democritus-strings package has been uploaded by us.

![image](https://user-images.githubusercontent.com/58363074/187009667-72cbefd1-51cc-4252-99f6-c3cc56d5d22c.png)

The democritus-strings package can be successfully installed using `pip install d8s-xml==0.1.0`

![image](https://user-images.githubusercontent.com/58363074/187009807-1a61096f-9893-4f90-b5ab-20e0306e7d5a.png)

Suggestion: remove version 0.1.0 of this project in PyPI

**Comment by fhightower** [comment]
Thanks for raising this issue (and all of the similar ones) @di1l0o! I'll take a look.

I probably will not bother removing v0.1.0 from pypi as no one should be using that version, but I'll give it some thought.
